# Generated by Django 5.2.17 on 2026-09-09 19:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('source', models.CharField(default='Steam', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itad_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('current_best_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('current_best_store', models.CharField(blank=True, max_length=100, null=True)),
                ('historical_low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('historical_low_store', models.CharField(blank=True, max_length=100, null=True)),
                ('last_price_sync', models.DateTimeField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='games', to='games.genre')),
                ('tags', models.ManyToManyField(blank=True, related_name='games', to='games.tag')),
            ],
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preferred_store', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cut_percentage', models.PositiveSmallIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='games.game')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='GameOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNPLAYED', 'Unplayed'), ('PLAYING', 'Playing'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned'), ('WISHLIST', 'Wishlist')], default='UNPLAYED', max_length=20)),
                ('platform', models.CharField(choices=[('STEAM', 'Steam'), ('GOG', 'GOG'), ('EPIC', 'Epic Games'), ('SWITCH', 'Nintendo Switch'), ('PS5', 'PlayStation 5'), ('XBOX', 'Xbox Series X/S')], max_length=20)),
                ('access_type', models.CharField(choices=[('DIGITAL', 'Digital Purchase'), ('PHYSICAL', 'Physical Disc/Cartridge'), ('GAME_PASS', 'Xbox Game Pass'), ('PS_PLUS', 'PlayStation Plus Extra/Premium')], default='DIGITAL', max_length=20)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='games.game')),
            ],
            options={
                'unique_together': {('game', 'platform')},
            },
        ),
    ]
