# Generated by Django 5.2.17 on 2026-09-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='boxart_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_appid',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gameownership',
            name='platform',
            field=models.CharField(choices=[('STEAM', 'Steam'), ('GOG', 'Good Ol Games'), ('EPIC', 'Epic Games'), ('SWITCH 2', 'Nintendo Switch 2'), ('PS5', 'PlayStation 5'), ('XBOX', 'Xbox Series X/S')], max_length=20),
        ),
    ]
