# Generated by Django 5.2.17 on 2026-09-11 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_options_alter_genre_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('STEAM', 'Steam Wishlist'), ('ITAD', 'ITAD Waitlist'), ('BOTH', 'Steam & ITAD')], default='STEAM', max_length=10)),
                ('itad_price_cut', models.IntegerField(blank=True, help_text='Target discount percentage', null=True)),
                ('itad_price_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Target price cap', max_digits=10, null=True)),
                ('steam_priority', models.IntegerField(default=0, help_text='Steam wishlist order index')),
                ('added_to_wishlist_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['steam_priority', '-created_at'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
